merge_protections:
  - name: Enforce checks passing
    description: Make sure that checks are not failing on the PR, and reviewers approved
    if:
      - base = master
    success_conditions:
      - "#approved-reviews-by >= 1"            # At least 1 approval
      - "#changes-requested-reviews-by == 0"   # No reviewer asked for changes
      - or:
        - check-success="gcc-openmp / dbg"
        - check-skipped="gcc-openmp / dbg"
      - or:
        - check-success="gcc-openmp / sp"
        - check-skipped="gcc-openmp / sp"
      - or:
        - check-success="gcc-openmp / fpe"
        - check-skipped="gcc-openmp / fpe"
      - or:
        - check-success="gcc-openmp / opt"
        - check-skipped="gcc-openmp / opt"
      - or:
        - check-success="gcc-cuda / dbg"
        - check-skipped="gcc-cuda / dbg"
      - or:
        - check-success="gcc-cuda / sp"
        - check-skipped="gcc-cuda / sp"
      - or:
        - check-success="gcc-cuda / opt"
        - check-skipped="gcc-cuda / opt"
      - or:
        - check-success="cpu-gcc / ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.scream-output-preset-2"
        - check-skipped="cpu-gcc / ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.scream-output-preset-2"
      - or:
        - check-success="cpu-gcc / ERS_P16_Ln22.ne30pg2_ne30pg2.FIOP-SCREAMv1-DP.scream-dpxx-arm97"
        - check-skipped="cpu-gcc / ERS_P16_Ln22.ne30pg2_ne30pg2.FIOP-SCREAMv1-DP.scream-dpxx-arm97"
      - or:
        - check-success="cpu-gcc / ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.scream-small_kernels--scream-output-preset-5"
        - check-skipped="cpu-gcc / ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.scream-small_kernels--scream-output-preset-5"
      - or:
        - check-success="cpu-gcc / SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.scream-mam4xx-all_mam4xx_procs"
        - check-skipped="cpu-gcc / SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.scream-mam4xx-all_mam4xx_procs"
      - or:
        - check-success=cpu-gcc
        - check-skipped=cpu-gcc

pull_request_rules:
    - name: Automatic merge when CI passes and approved
      conditions:
        - check-success="Mergify Merge Protections" # Pass if merge protection rule passes
        - "label=CI: automerge"
        - base=master
      actions:
        merge:
          method: merge
          commit_message_template: |
            Merge pull request #{{number}} from {{head}}

            Automatically merged using mergify
            PR title: {{title}}
            PR author: {{author}}
            PR labels: {{label}}
