merge_protections:
  - name: Enforce checks passing
    description: Make sure that checks are not failing on the PR, and reviewers approved
    if:
      - base = master
    success_conditions:
      - "#approved >= 1"            # At least 1 approval
      - "#changes-requested == 0"   # No reviewer asked for changes
      - or:
        - and:
          - check-success=eamxx-sa/gcc-openmp/sp
          - check-success=eamxx-sa/gcc-openmp/dbg
          - check-success=eamxx-sa/gcc-openmp/fpe
          - check-success=eamxx-sa/gcc-openmp/opt
        - check-skipped="eamxx-sa/gcc-openmp/${{matrix.build_type}}"
      - or:
        - and:
          - check-success=eamxx-sa/gcc-cuda/sp
          - check-success=eamxx-sa/gcc-cuda/dbg
          - check-success=eamxx-sa/gcc-cuda/opt
        - check-skipped="eamxx-sa/gcc-cuda/${{matrix.build_type}}"
      - or:
        - and:
          - check-success=eamxx-v1/cpu-gcc/ERS_Ln9.ne4_ne4.F2000-SCREAMv1-AQP1.scream-output-preset-2
          - check-success=eamxx-v1/cpu-gcc/ERS_P16_Ln22.ne30pg2_ne30pg2.FIOP-SCREAMv1-DP.scream-dpxx-arm97
          - check-success=eamxx-v1/cpu-gcc/ERS_Ln22.ne4pg2_ne4pg2.F2010-SCREAMv1.scream-small_kernels--scream-output-preset-5
          - check-success=eamxx-v1/cpu-gcc/SMS_D_Ln5.ne4pg2_oQU480.F2010-SCREAMv1-MPASSI.scream-mam4xx-all_mam4xx_procs
        - check-skipped="eamxx-v1/cpu-gcc-/${{matrix.test.short_name}}"
      - or:
        - check-success=eamxx-scripts/cpu-gcc
        - check-skipped=eamxx-scripts/cpu-gcc
