name: 'Check Skip Labels'
description: 'Check for specific skip labels in a pull request'
inputs:
  skip_labels:
    description: 'Comma-separated list of skip labels'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Pull Request Labels
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching pull request labels..."
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          LABELS="${{ toJson(github.event.pull_request.labels) }}"
        elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
          prNumber="${{ github.payload.pull_request.number }}"
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$prNumber")
          LABELS=$(echo "$response" | jq -r '.labels | map(.name) | join(",")')
        fi
        echo "labels=$LABELS" >> $GITHUB_ENV
      shell: sh
    - name: Check for Skip Labels
      run: |
        echo "Checking for skip labels..."
        IFS=',' read -r -a SKIP_LABELS <<< "${{ inputs.skip_labels }}"
        IFS=',' read -r -a LABEL_ARRAY <<< "$labels"

        for label in "${SKIP_LABELS[@]}"; do
          for pr_label in "${LABEL_ARRAY[@]}"; do
            if [[ "$pr_label" == "$label" ]]; then
              echo "Found skip label '$label'. Skipping this job."
              exit 0  # Exit with success status
            fi
          done
        done
        echo "No relevant skip labels found. Continuing with the job."
      shell: sh
