name: gh-standalone

on:
  pull_request:
    branches: [ master ]
    paths:
      # first, yes to these
      - '.github/workflows/eamxx-gh-ci-standalone.yml'
      - 'cime_config/**'
      - 'components/eam/**'
      - 'components/eamxx/**'
      - 'components/elm/**'
      - 'driver-moab/**'
      - 'driver-mct/**'
      - 'components/homme/**'
      # second, no to these
      - '!components/eam/docs/**'
      - '!components/eam/mkdocs.yml'
      - '!components/eamxx/docs/**'
      - '!components/eamxx/mkdocs.yml'
      - '!components/elm/docs/**'
      - '!components/elm/mkdocs.yml'

  workflow_dispatch:

jobs:

  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          # TODO: add opt, dbg, etc. here once we stabilize testing
          # TODO: note that currently, there is a fail in atm_proc test
          # TODO: components/eamxx/src/share/tests/atm_process_tests.cpp
          # TODO: REQUIRE (dag.has_unmet_dependencies());
          # TODO: but only on some machines...
          - sp
    container: 
      image: ghcr.io/e3sm-project/containers-ghci:ghci-0.1.2

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: standalone
        env:
          SHELL: sh
        run: |
          # TODO: get rid of this extra line if we can?
          git config --global safe.directory '*'
          ./components/eamxx/scripts/test-all-scream -m ghci-oci -t ${{ matrix.test }}
    # TODO: add logging...
    #   - 
    #     name: Artifacts
    #     uses: actions/upload-artifact@v4
    #     if: ${{ always() }}
    #     with:
    #       name: ${{ matrix.test }}
    #       path: |
    #         /projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
    #         /projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
    #         /projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
    #         /projects/e3sm/scratch/${{ matrix.test }}*/run/*.cprnc.out
